apps/front/urls.py
from django.urls import path
from .views import front
from apps.login.views import Login

urlpatterns = [
    path('', front, name='front'),
    # path('register/', register_page, name='register'),
    # path('signup/', signup, name='signup'),
    path('login/', Login.as_view(), name='login'),
]

apps/object/urls.py
from django.urls import path
from .views import create_object, submit_object, search_object, ObjectList, SearchObject

app_name = 'object'

urlpatterns = [
    path('', create_object, name='createobject'),
    path('submitobject/', submit_object, name='submitobject'),
    # path('searchobject/', search_object, name='searchobject'),
    path('searchobject/', SearchObject.as_view(), name='searchobject'),
    path('objectlist', ObjectList.as_view(), name='objectlist')
]

apps/usermanagement/urls.py
from django.urls import path
from . import views

app_name = "usermanagement"


urlpatterns = [
    path('', views.GroupManagement.as_view(), name='groups_list'),
    path('create_group/', views.CreateGroup.as_view(), name='create_group'),
    path('edit_group/<groupid>/', views.EditGroup.as_view(), name='edit_group'),
    path('del_group/<groupid>', views.DelGroup.as_view(), name='del_group'),
    path('user_list/', views.UserManagement.as_view(), name='user_list'),
    path('add_user/<groupid>', views.AddUser.as_view(), name='user_add'),
    path('del_user/<groupid>/<userid>', views.DelUser.as_view(), name='del_user'),
    path('user_del_group/<groupid>/<userid>', views.UserDelGroup.as_view(), name='user_del_group'),
    path('manage_group/<userid>', views.UserGroupManage.as_view(), name='manage_group'),
    path('user_state/<userid>/<operateid>', views.UserEnableOrForbidden.as_view(), name='user_state')
]

autotestplant/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.login.views import LogOut

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('apps.front.urls')),
    path('homepage/', include('apps.homepage.urls')),
    path('logout/', LogOut.as_view(), name='logout'),
    path('createobject/', include('apps.object.urls')),
    path('register/', include('apps.register.urls')),
    path('product/', include('apps.product.urls')),
    path('testcase/', include('apps.testcases.urls')),
    path('api/', include('apps.api.urls')),
    path('tasklist', include('apps.task.urls')),
    path('groups_list/', include('apps.usermanagement.urls'))
]

apps/front/models.py
from django.db import models

apps/product/models.py
from django.db import models


class Products(models.Model):
    object_id = models.ForeignKey('object.Objcets', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    url = models.URLField()
    creat_time = models.DateTimeField(auto_now_add=True, null=True)
    describe = models.TextField(max_length=1000)
    state = models.BooleanField(default=1)

    class Meta:
        db_table = 'products'

apps/usermanagement/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User


class GroupExtension(models.Model):
    group = models.OneToOneField(Group, on_delete=models.CASCADE, related_name='group_extension')
    create_time = models.DateTimeField(auto_now_add=True)
    create_user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='group_user', null=True)
    group_state = models.BooleanField(default=True)
    update_time = models.DateTimeField(auto_now=True)

    @receiver(post_save, sender=Group)
    def create_group_extension(sender, instance, created, **kwargs):
        if created:
            GroupExtension.objects.create(group=instance)
        else:
            instance.group_extension.save()

    class Meta:
        db_table = 'groupextension'

apps/front/views.py
from django.shortcuts import render


def front(request):
    return render(request, 'page-login.html')

apps/usermanagement/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, View
from django.contrib.auth.models import Group, User
from django.contrib.auth.models import Permission
from django.db.models import F


class GroupManagement(ListView):
    model = Group  # 对应的模型名称
    template_name = 'groupmanagement.html'  # 对应的模板
    paginate_by = 20  # 每页显示条数
    context_object_name = 'groups'  # 模板引用上下文时使用的名称
    ordering = 'id'  # 根据id排序
    page_kwarg = 'p'  # 页码参数

    # def get_context_data(self, **kwargs):
    #     context = super(GroupManagement, self).get_context_data(**kwargs)

    def get_queryset(self):
        # print("-*"*40, Group.objects.all())
        group_list = Group.objects.filter(group_extension__group_state=1)

        return group_list


class CreateGroup(View):
    """创建组"""
    def get(self, request, *args, **kwargs):
        # user = request.user
        # print(type(user))
        # user = request.session.items()
        # user = request.session.get()
        permissions = Permission.objects.filter().order_by('id')
        return render(request, 'creategroup.html', {'permissions': permissions})

    def post(self, request, *args, **kwargs):
        userid = request.user.id    # 获取登录用户的id
        user = User.objects.get(id=userid)
        group_name = request.POST.get('group_name')
        group = Group.objects.create(name=group_name)    # 创建组
        group.group_extension.create_user = user
        group_right = request.POST.getlist('group_right')
        permissions = Permission.objects.filter(codename__in=group_right)    # 把需要添加的权限转换为queryset
        group.permissions.set(permissions)    # 为组添加权限
        group.save()
        return redirect('usermanagement:groups_list')


class EditGroup(View):
    def get(self, request, groupid, *args, **kwargs):
        editgroup = Group.objects.get(id=groupid)
        permissions = Permission.objects.filter().order_by('id')

        return render(request, 'edit-group.html', {'group': editgroup, 'permissions': permissions})

    def post(self, request, groupid, *args, **kwargs):
        userid = request.user.id  # 获取登录用户的id
        user = User.objects.get(id=userid)
        group_name = request.POST.get('group_name')
        group = Group.objects.get(id=groupid)
        group.group_extension.create_user = user
        group_right = request.POST.getlist('group_right')
        permissions = Permission.objects.filter(codename__in=group_right)  # 把需要添加的权限转换为queryset
        group.permissions.set(permissions)  # 为组添加权限
        group.save()
        return redirect('usermanagement:groups_list')

class DelGroup(View):
    def get(self, request, groupid, *args, **kwargs):
        group = Group.objects.get(id=groupid)
        group.group_extension.group_state = False
        group.save()
        group_list = Group.objects.filter(group_extension__group_state=1)
        return render(request, 'groupmanagement.html', {'groups': group_list})

class AddUser(View):
    """向用户组添加用户"""
    def get(self, request, groupid, *args, **kwargs):
        group = Group.objects.get(id=groupid)
        user_list = group.user_set.all()
        print(user_list)
        return render(request, 'add-user.html', {'users': user_list, 'group': group})

    def post(self, request, groupid, *args, **kwargs):
        group = Group.objects.get(id=groupid)
        users_id = request.POST.get('users_id')
        user_name = request.POST.get('user_name')
        if user_name:
            add_user = User.objects.get(username=user_name)
            add_user.groups.add(group)


        return redirect('usermanagement:groups_list')

class DelUser(View):
    """从用户组删除用户"""
    def get(self, request, groupid, userid):
        group = Group.objects.get(id=groupid)
        user = User.objects.get(id=userid)
        user.groups.remove(group)
        return redirect('usermanagement:user_add', groupid)

class UserManagement(ListView):
    model = User  # 对应的模型名称
    template_name = 'usermanagement.html'  # 对应的模板
    paginate_by = 20  # 每页显示条数
    context_object_name = 'users'  # 模板引用上下文时使用的名称
    ordering = 'id'  # 根据id排序
    page_kwarg = 'p'  # 页码参数

    # def get_context_data(self, **kwargs):
    #     context = super(GroupManagement, self).get_context_data(**kwargs)

    # 获取上下文数据
    def get_context_data(self, **kwargs):
        context = super(UserManagement, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pages = self.get_pagination_data(paginator, page_obj, 2)
        context.update(pages)
        return context

    def get_queryset(self):
        # print("-*"*40, Group.objects.all())
        user_list = User.objects.filter()

        return user_list

    # 生成页码
    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        count_page = paginator.num_pages
        left_has_more = False
        right_has_more = False
        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)
        if current_page >= count_page - around_count - 1:
            right_pages = range(current_page + 1, count_page + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': count_page
        }

class UserGroupManage(View):
    """管理用户名下的用户组"""
    def get(self, request, userid, *args, **kwargs):
        user = User.objects.get(id=userid)
        group_list = user.groups.all()
        print(group_list)
        return render(request, 'user-groups-manage.html', {'user': user, 'groups': group_list})

    def post(self, request, userid, *args, **kwargs):
        user = User.objects.get(id=userid)
        group_name = request.POST.get('group_name')
        if group_name:
            group = Group.objects.get(name=group_name)
            user.groups.add(group)
        return redirect('usermanagement:user_list')

class UserDelGroup(DelUser):
    """从用户管理删除用户加入的组"""
    def get(self, request, groupid, userid):
        super(UserDelGroup, self).get(request, groupid, userid)
        return redirect('usermanagement:manage_group', userid)

class UserEnableOrForbidden(View):
    """用户禁用和启用"""
    def get(self, request, userid, operateid, *args, **kwargs):
        user = User.objects.get(id=userid)
        if operateid == '1' and user.is_active is False:    # 1为启用
            user.is_active = 1
        elif operateid == '2' and user.is_active:    # 2为禁用
            user.is_active = 0
        user.save()
        return redirect('usermanagement:user_list')

templates/add-user.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-lg-6">
        <div class="card">
            <div class="card-title">
                <h4>{{ group.name }}--管理组用户</h4>

            </div>
            <div class="card-body">
                <div class="basic-form">
                    <form method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <label>用户名</label>
                            <input name="user_name" class="form-control" placeholder="需要添加的用户名">
                        </div>
                        <div class="form-group">
                            <label>已添加用户 </label>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>用户名</th>
                                                <th>状态</th>
                                                <th>手机号</th>
                                                <th>操作</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for each_user in users %}
                                            <tr>
                                                <th scope="row">{{ each_user.id }}</th>
                                                <td>{{ each_user.username }}</td>
                                                <td><span class="badge badge-primary">{{ each_user.is_active }}</span></td>
                                                <td>{{ each_user.extension.phone_number }}</td>
                                                <td class="color-primary">
                                                    <a href="{% url 'usermanagement:del_user' groupid=group.id userid=each_user.id %}" type="button" class="btn btn-danger btn-flat btn-addon btn-sm m-b-10"style="padding-left: 8px;">删除</a>
                                                </td>
                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                        <button type="submit" class="btn btn-success">确定</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/batch-response.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col-md-6">
        <div class="card">
            <h4 class="card-title">执行结果</h4>
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <div class="card-title">
                    <h4>{{ product.name }} </h4>
                    </div>
                    <thead>
                        <tr>
                            <th>接口id</th>
                            <th>接口名称</th>
                            <th>执行结果</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for each_response in response %}
                            <tr>
                                <td>{{ each_response.response.0.id }}</td>
                                <td>{{ each_response.response.0.name }}</td>
                                {% if each_response.assertion.info == '校验成功' %}
                                    <td bgcolor="green">{{ each_response.assertion.info }}</td>
                                {% elif each_response.assertion.info == None and each_response.response.1.status_code == 200%}
                                    <td bgcolor="green">{{ each_response.response.1.status_code }}</td>
                                {% elif each_response.assertion.info == '校验失败'%}
                                    <td bgcolor="red">{{ each_response.assertion.info }}</td>
                                {% elif each_response.assertion.info == None and each_response.response.1.status_code != 200%}
                                    <td bgcolor="red">{{ each_response.response.1.status_code }}</td>
                                {% endif %}
                                <td>
                                    <!-- /# 这里写操作功能 -->


                                </td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
        <div class="card">
            <div class="card-body p-b-0">
                <h4 class="card-title">接口响应</h4>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs customtab2" role="tablist">
                    <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home7" role="tab"><span class="hidden-sm-up"><i class="ti-home"></i></span> <span class="hidden-xs-down">header</span></a> </li>
                    <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#profile7" role="tab"><span class="hidden-sm-up"><i class="ti-user"></i></span> <span class="hidden-xs-down">response</span></a> </li>
                    <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#messages7" role="tab"><span class="hidden-sm-up"><i class="ti-email"></i></span> <span class="hidden-xs-down">校验结果</span></a> </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="home7" role="tabpanel">
                        {% for each_response in response %}
                            <div class="p-20">
                                <h5>{{ each_response.response.0.name }}</h5>
                                <p>State code: {{ each_response.response.1.status_code }}</p>
                                <p>request url: {{ each_response.response.1.url }}</p>

                            </div>
                        {% endfor %}
                    </div>
                    <div class="tab-pane  p-20" id="profile7" role="tabpanel">
                        {% for each_response in response %}
                            <div class="p-20">
                                <h5>{{ each_response.response.0.name }}</h5>
                                <p>{{ each_response.response.1.text }}</p>

                            </div>
                        {% endfor %}
                    </div>
                    <div class="tab-pane p-20" id="messages7" role="tabpanel">
                        {% for each_response in response %}
                            <h5>{{ each_response.response.0.name }}</h5>
                            <p>校验结果: {{ each_response.assertion.info }}</p>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/search-object.html
{% extends "base.html" %}

{% block content %}

    <!-- /# row -->
    <div class="col-lg-6">
        <div class="card">
            <div class="button-list">
                <a href="{% url 'object:createobject' %}" type="button" class="btn btn-primary btn-flat btn-addon m-b-10 m-l-5"><i class="ti-plus"></i>新增项目</a>
                <button type="submit" class="btn btn-pink btn-flat btn-addon m-b-10"><i class="ti-search"></i>搜索</button>
            </div>

            <form action="{% url 'object:searchobject' %}" method="post">
                {% csrf_token %}

                <table>
                    <thead>
                    <tr>
                        <th></th>
                    </tr>
                    <tr>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <input type="search" class="form-control input-sm" placeholder="请输入项目名称" aria-controls="bootstrap-data-table-export" name="searchobjectname" value= {{ kw }}>
                            </td>
                            <td><button type="submit" class="btn btn-pink btn-flat btn-addon m-b-10"><i class="ti-search"></i>搜索</button></td>
                        </tr>
{#                        <tr>#}
{#                            <td>#}
{#                                <button type="submit" class="btn btn-pink btn-flat btn-addon m-b-10"><i class="ti-search"></i>搜索</button>#}
{#                            </td>#}
{#                        </tr>#}
                    </tbody>

                </table>

            </form>

        </div>
        <!-- /# card -->


    {% for eachobject in objects %}

        <section id="main-content" class="card-body">
            <div class="row">
                <!-- /# column -->
                <div class="col-lg-6">
                    <div class="card" style="width: 1800px;">
                        <div class="card-title">
                            <h4>{{ eachobject.object_name }} </h4>
                            <div style = "text-align:right;">
                                <a href="{% url 'createproduct' object_id=eachobject.id %}" type="button" class="btn btn-primary btn-flat btn-addon m-b-10 m-l-5"><i class="ti-plus"></i>新增产品</a>
                                <a href="{% url 'delobject' object_id=eachobject.id %}" type="button" class="btn btn-success btn-flat btn-addon m-b-10 m-l-5"><i class="ti-minus"></i>删除项目</a>
                                <a href="{% url 'editobject' object_id=eachobject.id %}" type="button" class="btn btn-danger btn-flat btn-addon m-b-10 m-l-5"><i class="ti-settings"></i>编辑</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>产品名称</th>
                                            <th>url</th>
                                            <th>创建日期</th>
                                            <th>产品描述</th>
                                            <th>操作</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    {% for eachproduct in eachobject.products_set.values %}
                                        {% if eachproduct.state %}
                                            <tr>
                                                <th scope="row">1</th>
                                                <td>{{ eachproduct.name }}</td>
                                                <td><span class="badge badge-primary">{{ eachproduct.url }}</span></td>
                                                <td>{{ eachproduct.creat_time }}</td>
                                                <td class="color-primary">{{ eachproduct.describe }}</td>
                                                <td class="button-list">
                                                    <a href="{% url 'editproduct' object_id=eachobject.id product_id=eachproduct.id %}" type="button" class="btn btn-info btn-flat btn-addon btn-sm m-b-10 m-l-5" style="padding-left: 8px;">编辑</a>
                                                    <a href="{% url 'delproduct' product_id=eachproduct.id %}" type="button" class="btn btn-danger btn-flat btn-addon btn-sm m-b-10"style="padding-left: 8px;">删除</a>
                                                </td>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /# row -->

        </section>

    {% endfor %}
    {% include 'page-num-search.html' %}
    </div>

{% endblock %}

templates/tasklist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet" href="{% static 'css/an-skill-bar.css' %}">

    {% for each in objects %}
        <section id="{{ each.1.id }}">
            <form action="{% url 'exetestcases' productid=each.1.id %}" method="post" id="{{ each.1.id }}">
            {% csrf_token %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="bootstrap-data-table-panel">
                                <div class="table-responsive">
                                    <table id="{{ each.1.id }}" class="table table-striped table-bordered">
                                        <div class="card-title">
                                        <h4>{{ each.0.object_name }} -- {{ each.1.name }} </h4>
                                        </div>
                                        <thead>
                                            <tr>
                                                <th>用例id</th>
                                                <th>用例名称</th>
                                                <th>执行进度</th>
                                                <th>操作</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for each_testcase in each.2 %}
                                                <tr>
                                                    <td>{{ each_testcase.id }}</td>
                                                    <td>{{ each_testcase.name }}</td>
                                                    <td></td>
                                                    <td>
                                                        <!-- /# 这里写操作功能 -->


                                                    </td>
                                                </tr>
                                            {% endfor %}

                                        </tbody>
                                    </table>
                                    <div class="card-footer">
                                        <div class="card-title">
                                            循环次数:
                                            <input type="text" class="form-control input-sm m-b-10 m-l-5" style="width: 86px;" name="loopnumber" value="1">
                                            循环间隔时间:
                                            <input type="text" class="form-control input-sm m-b-10 m-l-5" style="width: 86px;" name="intervaltime" value="0">
                                        </div>
                                        <div class="card-title">
                                            预计执行时间:
                                            <input type="time" class="form-control input-sm m-b-10 m-l-5" style="width: 86px;" name="exe_time">
                                        </div>

                                        <input type="submit" class="btn btn-success m-b-10 m-l-5" value="执行">

                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /# card -->
                    </div>
                    <!-- /# column -->
                </div>
            </form>
        </section>
    {% endfor %}

<script src="{% static 'js/jquery-1.11.0.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/an-skill-bar.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


{% endblock %}

templates/user-groups-manage.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-lg-6">
        <div class="card">
            <div class="card-title">
                <h4>{{ user.username }}--管理组</h4>

            </div>
            <div class="card-body">
                <div class="basic-form">
                    <form method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <label>组名</label>
                            <input name="group_name" class="form-control" placeholder="需要添加的用户组名称">
                        </div>
                        <div class="form-group">
                            <label>已添加用户组 </label>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>组名</th>
                                                <th>操作</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for each_group in groups %}
                                            <tr>
                                                <th scope="row">{{ each_group.id }}</th>
                                                <td>{{ each_group.name }}</td>
                                                <td class="color-primary">
                                                    <a href="{% url 'usermanagement:user_del_group' groupid=each_group.id userid=user.id %}" type="button" class="btn btn-danger btn-flat btn-addon btn-sm m-b-10"style="padding-left: 8px;">删除</a>
                                                </td>
                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                        <button type="submit" class="btn btn-success">确定</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}